name: Azure Virtual Machine Environment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      id-token: write
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install azure-cli
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      
    - name: Az Login
      uses: azure/login@v1
      with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SCRT }}","subscriptionId":"${{ secrets.SUB_ID }}","tenantId":"${{ secrets.TEN_ID }}"}'
    
    - name: Checkout
      uses: actions/checkout@v3.5.3
        
    - name: Replace Tokens
      uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '__'
        tokenSuffix: '__'
        files: '["**/*.sh"]'
      env:
        groupName: ${{groupName}}
        groupLocation: ${{groupLocation}}
        
    - name: Script Testing
      run: cat ResourceGroup.sh
        
#     - name: Azure CLI script file
#       uses: azure/CLI@v1
#       with:
#           azcliversion: 2.30.0
#           inlineScript: |
#             chmod +x $GITHUB_WORKSPACE/*.sh
#             $GITHUB_WORKSPACE/ResourceGroup.sh
